includes: config/datasets/ood_cv.yaml

name: ood-cv_cls
root_path: data/OOD_CV_NeMo_cls

image_sizes:
    aeroplane: [512, 512]
    bicycle: [512, 512]
    boat: [512, 512]
    bus: [512, 512]
    chair: [512, 512]
    car: [512, 512]
    diningtable: [512, 512]
    motorbike: [512, 512]
    sofa: [512, 512]
    train: [512, 512]

skip_3d_anno: true
